version: "2"
services:
  auth:
    container_name: auth
    restart: always
    build: .
    ports:
      - "2000:2000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"